#url: http://localhost:4000
#baseurl: /
blogUrl: https://blog.hacking.law

# Site settings
title: Berlin Legal Tech
email: we.are@hacking.law
description: "Die Berlin Legal Tech ist ein einzigartiges Event im Legal Tech Bereich, gegründet und geleitet von Legal Tech Pionier Prof. Dr. Stephan Breidenbach und dem auf Blockchain-Technologie spezialisierten Rechtsanwalt und Unternehmer Florian Glatz."


# Team names, titles and social links
people:
- name: Stephan Breidenbach
  pic: sb
  position: Founder, Co-Organiser
  social:
    - title: envelope-o
      url: mailto:stephan.breidenbach@legaltech.center
    - title: twitter
      url: https://twitter.com/stebreidenbach

- name: Florian Glatz
  pic: fg
  position: Founder, Co-Organiser
  social:
    - title: envelope-o
      url: mailto:florian.glatz@legaltech.center
    - title: twitter
      url: https://twitter.com/heckerhut

- name: Natalie Eichler
  pic: ne
  position: Head of Event
  social:
    - title: envelope-o
      url: mailto:ne@blockchain.lawyer

- name: Alice Kohn
  pic: ak
  position: Head of Media
  social:
    - title: envelope-o
      url: mailto:ne@blockchain.lawyer
    - title: twitter
      url: https://twitter.com/AliceKohn

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - network:
    title: info@legaltech.center
    url: mailto:info@legaltech.center


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty